//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Countries_Adapters
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public short IdCountry { get; set; }
        public string NameCountry { get; set; }
        public bool Active { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
